{
 "title": "Flower Counter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wookies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Wookies" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(flowers_per_second{namespace=\"flower-market\", container=\"wookie\"})"
    }
   ]
  },
  {
   "title": "Wookies",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Flowers" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(flowers_per_second)" }
   ]
  },
  {
   "title": "Flowers per Wookie per Second",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flowers_per_second", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Wookie Performance",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "FPS" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "flowers_per_second", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Wookies",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(flowers_per_second{namespace=\"flower-market\", container=\"wookie\"})",
     "legendFormat": "Wookies"
    }
   ]
  }
 ]
}