apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flower-worker-fps
  labels:
    app: flower-counter-monitor
  namespace: monitoring
spec:
  endpoints:
    - targetPort: 8080
      interval: 5s
  namespaceSelector:
    matchNames:
    - flower-market
  selector:
    matchLabels:
      app: flower-counter-worker