apiVersion: v1
kind: Service
metadata:
  name: wookie-metrics
  labels:
    app: flower-counter-worker
  namespace: flower-market
spec:
  type: LoadBalancer
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  selector:
    app: a-new-hope-worker