apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-new-hope-wookie
  labels:
    app: flower-counter-worker
  namespace: flower-market
spec:
  selector:
    matchLabels:
      app: a-new-hope-worker
  template:
    metadata:
      labels:
        app: a-new-hope-worker
      annotations:
        auto-management/bitfusion: "yes"
        bitfusion-client/os: "ubuntu20"
        bitfusion-client/version: "401"
    spec:
      containers:
      - name: wookie
        image: harbor-repo.vmware.com/dockerhub-proxy-cache/mylesagray/a-new-hope-worker:d018d89
        imagePullPolicy: Always
        command: ["python ./a-new-hope-worker/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --data_format=NCHW --batch_size=32 --model=resnet50 --num_batches=200 --variable_update=replicated --local_parameter_device=gpu  --nodistortions"]
        ports:
        - name: metrics
          containerPort: 8080
        env:
          - name: BATCHES
            value: "2000"
        resources:
          requests:
            ephemeral-storage: 10M
          limits:
            bitfusion.io/gpu-amount: 1 
            bitfusion.io/gpu-percent: 100