apiVersion: v1
kind: Namespace
metadata:
  name: flower-market
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-new-hope
  labels:
    app: flower-counter
  namespace: flower-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-new-hope-dashboard
  template:
    metadata:
      labels:
        app: a-new-hope-dashboard
    spec:
      containers:
      - name: dashboard
        image: vhojan/a-new-hope-dashboard
        ports:
        - name: http
          containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-new-hope-worker
  labels:
    app: flower-counter
  namespace: flower-market
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-new-hope-worker
  template:
    metadata:
      labels:
        app: a-new-hope-worker
    spec:
      containers:
      - name: worker
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flower-service
  labels:
    app: flower-counter
  namespace: flower-market
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: a-new-hope-dashboard
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: flower-autoscaler
  labels:
    app: flower-counter
  namespace: flower-market
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: a-new-hope-worker
  metrics:
  - type: External
    external:
      metricName: aggregate
      targetAverageValue: 200
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flower-fps
  labels:
    app: flower-counter-monitor
  namespace: monitoring
spec:
  endpoints:
    - targetPort: 80
      interval: 5s
  namespaceSelector:
    matchNames:
    - flower-market
  selector:
    matchLabels:
      app: flower-counter