apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: endor
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: best-effort-2xlarge
      count: 3
      storageClass: vsan-default-storage-policy
    workers:
      class: best-effort-2xlarge
      count: 4
      storageClass: vsan-default-storage-policy
  settings:
    storage:
      classes: ["vsan-default-storage-policy"]              #Named PVC storage classes
      defaultClass: vsan-default-storage-policy                     #Default PVC storage class